version: "2"
services:
  waitfordb:
      image: dadarek/wait-for-dependencies
      depends_on:
        - postgres
      command: postgres:5432

  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    volumes:
      - ./db/psgl:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
      - waitfordb
    environment:
        TZ: "Asia/Tokyo"
